### ISSUE TITLE
Probable false positive?

### ISSUE THREAD

**Issue by Lukiddo** [suurjaak/Skyperious#36]
Hi, apologies for being a bother, but I wanted to ask something.
I've been using Skyperious 3.2 'till now without a problem, and now I wanted to update it to 3.3.
Unfortunately, my Antivirus, Kaspersky, is now telling me that the download links are unsafe urls, and that the actual files seems to have troubles; A trojan for the 64bit installation, and a 'Hoax.Win32.ArchSMS.cjgjd' virus on the normal set up.

I wanted to know : is this a fake positive? If yes, why is Kaspersky signaling them as such?

Thank you in advance for an explanation.

**Comment by suurjaak** [comment]
Yes, this is a false positive. Because the Windows executable is a packed and compressed file containing various libraries, antivirus tools can sometimes misjudge it, as viruses use similar techniques.

This is not the first time an antivirus has raised a bogus flag, DrWeb [was reporting](https://www.virustotal.com/en/file/54010e520733e11c26590dfedc04d8165c071fa7d166906d2514e3865939ffc1/analysis/1381937015/) Skyperious 2.2 as "Trojan.Siggen5.44741".
I sent a report about this false positive to Kaspersky, hopefully they will update their virus definitions soon.

Thank you for bringing this to my attention!

**Comment by Lukiddo** [comment]
Oh I see. I expected it to be a bogus, but one might never be too sure.

Thank you a lot for the fast reply, and have a good day!

**Comment by suurjaak** [comment]
Got a reply from Kaspersky:

    Sorry, it was a false detection. It will be fixed in the next update.

Thanks again.
