### ISSUE TITLE
Add Viber support

### ISSUE THREAD

**Issue by asd-and-Rizzo** [suurjaak/Skyperious#39]
1. Installed Viber 5.1.2 for Windows
2. Installed skyperious_3.4.1_x64_setup.exe 
3. Login into Viber
4. Open C:\Users\%MY_NAME%\AppData\Roaming\ViberPC\%MYPHONENUMBER%\ folder.

Expected: `data.db` and `viber.db` are opened from mentioned folder.

Actual: Error as attached
![2015-07-05 14_27_27-greenshot](https://cloud.githubusercontent.com/assets/757125/8511498/0304cef8-2322-11e5-91dd-101d40eb2967.png)

`Error text: DatabaseError: file is encrypted or is not a database`

```
[Window Title]
Skyperious
[Main Instruction]
Could not open C:\Users\Dzmitry_Lahoda\AppData\Roaming\ViberPC\375255318270\viber.db.
[Content]
Not a valid SQLITE database?
[OK]
```

Notes:

0. http://suurjaak.github.io/Skyperious/index.html states  `Additionally, it doubles as a useful database tool for any SQLite file.`

1. Opened in `.db` files shows  in Notepad++ shows as first line of binary data  
`SQLite format 3`

2.  Viber installation folder contains `dll`s about `sqlite` - `qsqlite.dll` and `Qt5Sql.dll`, but no other `sql` related.

3. It `db` are really encrypted or some, may I provide some key or mechanism for Skyperious to open these?

**4. It would be nice Skyperious  to support other sqlite based chat**

**Comment by suurjaak** [comment]
I don't use Viber myself, but from the looks of it, its files should be ordinary SQLite databases, without any encryption. Skyperious should at least be able to open them as such.

Why this file was not readable, I do not know.. One possibility could be that Viber had the file locked, but from the screenshot it looks like Viber is not running.

Does the other file, data.db, get opened? What happens if you copy the file and open the copy?
Does another database program work, like SQLite Studio or SQLite Browser?

As for Skyperious having full support for other chat programs - would be nice indeed :) but I definitely do not have time to implement that on my own.

**Comment by asd-and-Rizzo** [comment]
I copied both db files into separate folder and these failed to open. Has no other SQLite software installed.

Also I moved above one directory mentioned into C:\Users\%MY_NAME%\AppData\Roaming\ViberPC\.

This directory has 2 db files opened successfully.

**Comment by suurjaak** [comment]
I investigated further, and turns out the problem is SQLite version: Viber uses a newer format (3.7 or higher), which the current default SQLite library (3.6) for Python 2 does not support.

I upgraded the SQLite library and compiled a new pre-release version, can you try this out:
http://erki.lap.ee/skyperious/skyperious_3.5d_x64.exe

**Comment by suurjaak** [comment]
New 3.5 release has an updated SQLite library, capable of reading newer format databases.
