### ISSUE TITLE
Ability to merge two chats within the same DB

### ISSUE THREAD

**Issue by ttyusupov** [suurjaak/Skyperious#50]
It would be great to have ability to merge two chats within the same DB, especially to fix duplicate chats introduced by #49

**Comment by suurjaak** [comment]
Closing this issue, as the program has become obsolete: Skype chat history is no longer available to third-party programs.

**Comment by deepspaceaxolotl** [comment]
Would like to reopen this issue! Looking through my database, most of the "chats" are actually group calls that generated a new chat every time, so some way to merge all of those depending on the participants would be excellent (ideally being able to uncheck ones that were intended to be separate group chats, and maybe some way of dealing with merging group chats with names where the named one(s) aren't the earliest created (picking what name to keep, basically)). (Also, thank you so much for this great software!)

**Comment by suurjaak** [comment]
Not sure if adding such functionality would be very relevant now that Skype will shut down in less than three weeks. 

If you like, and are familiar with SQL, you could tweak your local database for this manually. Table `Conversations` has column `alt_identity` which Skyperious uses internally to present multiple chats as a single merged chat (this is a historical thing from Skype version 7 that migrated conversation IDs to some new logic). 

If you update this column of these duplicate conference chats, to refer to the `Conversations.identity` of some "main" chat and reopen the database, Skyperious should show a single chat entry for these.

**Comment by deepspaceaxolotl** [comment]
Oh, I'm thinking of adding it in the context of the shutdown, because I want to be able to browse my old chats using Skyperious (or perhaps something else later down the line, but the database would obviously be the same) and collate all the group calls in a more sensible way. Was thinking other folks might end up with a similar problem with group calls (and group chats with the same people in general) so I thought a GUI to do this would be nice, particularly for us SQL noobs. It's good to know it's already possible to do, just manually, though! I'll see about giving it a shot at some later point perhaps, thank you!

**Comment by suurjaak** [comment]
The idea is not bad, in fact I have a good number of such duplicate group calls in my own database. I might add this feature at some point in the future.

**Comment by deepspaceaxolotl** [comment]
Thank you for considering it! (Could this issue be opened to keep track of the idea? So that people don't open duplicates if someone else has it.)

**Comment by suurjaak** [comment]
Please open a new issue instead, as the original request here was about doing a complex "Compare and merge" to fix actually duplicated chats that had duplicated messages. Which came about due to Skyperious not being continuously updated to handle changes in Skype.

**Comment by deepspaceaxolotl** [comment]
Ah, I'd misunderstood that, my bad! Will do, thank you!
