### ISSUE TITLE
Skyperious can't read Skype 8 databases

### ISSUE THREAD

**Issue by nqzt** [suurjaak/Skyperious#74]
Microsoft stops support for Skype 7 Destop for Windfows, and the current Skyperious version can’t open Skype 8 databases.

**Comment by jmvermeulen** [comment]
Same issue here

**Comment by 4evermaat** [comment]
you can still use so-called classic skype `7.40.0.104` for windows if you have the standalone installer for it.  But then you must disable automatic updates within the settings menu AND (and block `\updater\updater.exe`or similar file from accessing the internet.

Not sure when microsoft will stop supporting it.  I think since probably > 1/2 of the world is still connecting to it with legacy versions, then it is **not** advantageous to just cut it lose altogether [yet].

**Comment by jmvermeulen** [comment]
@4evermaat are you serious? The point is that in many use-cases you only get the database, no online access to the account.

**Comment by 4evermaat** [comment]
?? I'm still using 7.x now.  I used to use win7 and then when I upgraded, I went to win 8.1.  Never had windows 10, or skype 8 without first backing up the `.db` file.   When I saw that skype 8 was significantly different, I reverted back to skype 7 and have been using that ever since.

I think mobile version of Skype Lite I have skype 8.x, which is fine.

Not sure if they are geotagging.  I'm in Malaysia now and have used it heavily in Thailand (skype 7 on laptop) with no issues.

---

@jmvermeulen Perhaps I am misunderstanding you.

**Comment by miloush** [comment]
Yeah you cannot use 7.x anymore. I would welcome support of the new database too.

**Comment by flyingbird88** [comment]
Sykpe is forcing 7.x versions to 8.x update and also you cant use Skype anymore if you don't upgrade to 8.x

Waiting solution for new version.

**Comment by timikesmarky** [comment]
Skype 8 doesn't use a local database or save messages on the computer. So, skyperious can't fix it.

**Comment by 4evermaat** [comment]
@timikesmarky and others, can you "scrape" the chat info from the Skype program and then create your now database from that?

**Comment by miloush** [comment]
@timikesmarky `%LOCALAPPDATA%\Packages\Microsoft.SkypeApp_kzf8qxf38zg5c\LocalState\*.db`

**Comment by timikesmarky** [comment]
@4evermaat I have no idea.
@miloush I have no idea about the Universal app. I use Skype for Desktop as I'm on LTSC.

**Comment by miloush** [comment]
@timikesmarky `%APPDATA%\Microsoft\Skype for Desktop\IndexedDB\` then but that's LevelDB, not SqlLite so much less likely to be supported by Skyperious.

**Comment by timeakesmarky** [comment]
@4evermaat @miloush @flyingbird88 @jmvermeulen @nqzt
Those IndexedDB and levelDB files are just temp files.

I've found a solution.
- To read the history, you must go to your skype account settings and export chat history:
[http://go.skype.com/export](url)
- Then download Skype Parser from here:
[https://go.skype.com/skype-parser](url)
- Extract the zip files.
- Double click on the "index.html" file and click on "Choose file" button and select your "messages.json" file. This is inside the chat history you downloaded from skype.
- Now click on the "Load" button and you can read your history.

The skype's viewer is not as beautiful as skyperious. But that's what we get.

**Comment by 4evermaat** [comment]
Will skyperious eventually be able to read the exported tar and have its own "parser"?

**Comment by suurjaak** [comment]
Skype no longer keeps chat history in locally available files, at least none that I've been able to discover. 

And the solution that @timeakesmarky discovered is also no longer available.

**Comment by timeakesmarky** [comment]
> Skype no longer keeps chat history in locally available files, at least none that I've been able to discover.
> 
> And the solution that @timeakesmarky discovered is also no longer available.

The solution works fine, just tested now.

**Comment by suurjaak** [comment]
Strange. I tried it yesterday, and after login at http://go.skype.com/export, I got a 404 page. 

Tried it now, and I do see a page where chat history can be downloaded. Maybe it was a temporary hiccup on Skype servers.

**Comment by timeakesmarky** [comment]
The skype's json parser is really really terrible.
Could you please make a parser/viewer of the json history?

**Comment by suurjaak** [comment]
Wow, you're right. It's amazing how bad it all is, first in the steps the user is expected to take to get access to their own history, and secondly the viewer itself. And this is the official support from a multi-billion-dollar software corporation.. 

But I don't know if I have much interest left in fiddling with Skype stuff. I'll think about it. 

Although it would be nice to have all message history together in one place, maybe by merging that archive to an older main.db..

**Comment by timeakesmarky** [comment]
True, I've moved on to telegram which is the best currently with a separate desktop client like good old MSN messenger.

**Comment by suurjaak** [comment]
I've released a new version of Skyperious, v4.0, that can download new messages from Skype online service and save them in an existing main.db. Or it can create a new main.db with these online messages from scratch.

**Comment by timeakesmarky** [comment]
Any hope to convert already downloaded json history files from skype?

**Comment by suurjaak** [comment]
Perhaps in the next release, yes.

**Comment by timeakesmarky** [comment]
Thank you so much! <3

**Comment by suurjaak** [comment]
Actually, there is no need to convert the downloaded JSON history - the live sync option in Skyperious v4 downloads the same messages that the Skype export provides.

**Comment by timeakesmarky** [comment]
True if the chats are still on Skype. If exported and deleted from skype, no hope.

**Comment by suurjaak** [comment]
Ah, true. But why would somebody delete the chats from Skype if they wanted to retain chat history?

**Comment by timeakesmarky** [comment]
I downloaded the export files and deleted on skype as I had stopped using.

**Comment by 4evermaat** [comment]
This is very timely because now there is a 6 month limit on chat messages.....and now only 30 days on images.

So a weekly local backup of chats would be great to keep a permanent record.   And this could actually be automated in the cloud to keep off-site records.

**Comment by suurjaak** [comment]
> I downloaded the export files and deleted on skype as I had stopped using.

Aha, makes sense. 

I think I'll provide an option to merge the exported archive into an existing main.db.

**Comment by suurjaak** [comment]
> So a weekly local backup of chats would be great to keep a permanent record. And this could actually be automated in the cloud to keep off-site records.

Yep, you can automate this via the command-line interface that Skyperious has.

**Comment by suurjaak** [comment]
> Any hope to convert already downloaded json history files from skype?

@timeakesmarky Option to merge in the JSON history is available in the newest version, 4.1. On initial database page: Compare and merge -> Select a Skype chat history export archive from your computer.

**Comment by 4evermaat** [comment]
is there command line parameters available so that the program can be run silently (headless) and/or parameters to automate the download/merging?    This would enable regular backup capability using `task manager` for example.

**Comment by suurjaak** [comment]
@4evermaat https://suurjaak.github.io/Skyperious/help.html#commandline

**Comment by timeakesmarky** [comment]
> > Any hope to convert already downloaded json history files from skype?
> 
> @timeakesmarky Option to merge in the JSON history is available in the newest version, 4.1. On initial database page: Compare and merge -> Select a Skype chat history export archive from your computer.

Hey! Thanks for the feature. How to create an empty skype database? I don't have one. Can I create and merge the json to it?

**Comment by suurjaak** [comment]
> Hey! Thanks for the feature. How to create an empty skype database? I don't have one. Can I create and merge the json to it?

If you still have a working Skype account, log in with that - button "Create new database from Skype online" on the first program screen. I didn't provide an option to create a database from the export itself only because it seemed like too many buttons in the interface. Maybe I should.. 

> The number of messages in Skype json parser is 4289 and the number of messages in Skyperious after scanning was 4235. What are the missing messages? :)

Some missing messages are edits and deletions - the Skype export has separate entries for each edit and each message deletion, whereas in the original Skype database there is just one entry per message. Plus there are some types of messages that weren't in Skype before, like setting a conversation to public. 

If you notice something missing in the import that should be there, let me know. The current import logic is on the basis of my own chat history, and there are probably things I've missed.

**Comment by timeakesmarky** [comment]
> If you still have a working Skype account, log in with that - button "Create new database from Skype online" on the first program screen. I didn't provide an option to create a database from the export itself only because it seemed like too many buttons in the interface. Maybe I should..

I get an error logging in...
Failed to log in as 'user@email.com':
SkypeAuthException: (Couldn't retrieve t field from login response, <Response [200]>)

And after opening a database, in the "Online" tab, username is greyed out, can't be changed.
Microsoft has merged usernames and linked email addresses. I can only login with email address but Skyperious shows my username.

Yes, please provide an option to directly convert the json history. This program is my favourite. It doesn't have many buttons, it's very simple and user-friendly and amazing. :) You should actually be hired by Microsoft to work for Skype. The export is very beautiful.

> Some missing messages are edits and deletions - the Skype export has separate entries for each edit and each message deletion, whereas in the original Skype database there is just one entry per message. Plus there are some types of messages that weren't in Skype before, like setting a conversation to public.

I understand. It's just a few messages. So, it maybe the deletions.

> If you notice something missing in the import that should be there, let me know. The current import logic is on the basis of my own chat history, and there are probably things I've missed.

Certainly :)

**Comment by suurjaak** [comment]
> I get an error logging in... Failed to log in as 'user@email.com'

From what it looks like, this logging-in can sometimes fail, for no reason. Does the error persist if you try again? 

> Microsoft has merged usernames and linked email addresses. I can only login with email address but Skyperious shows my username.

The issue is that Microsoft accounts basically have two usernames, user@email.com and live:something, both of which work for logging in, but the actual Skype user ID is the live:something one. I should probably present the e-mail as the Skype name, but I'm not sure where to store it. In your older database, can you execute the following query in the SQL window:

```sql
SELECT skypename, signin_name, liveid_membername, msa_pmn FROM Accounts
```

In the result, is it so that the skypename is in the form live:something, and the signin_name in the form user@email.com? What about liveid_membername and msa_pmn?

**Comment by timeakesmarky** [comment]
> From what it looks like, this logging-in can sometimes fail, for no reason. Does the error persist if you try again?

Yes, it persists. Maybe it's related to 2-factor authentication or using an authenticator app to login?

> The issue is that Microsoft accounts basically have two usernames, [user@email.com](mailto:user@email.com) and live:something, both of which work for logging in, but the actual Skype user ID is the live:something one. I should probably present the e-mail as the Skype name, but I'm not sure where to store it. In your older database, can you execute the following query in the SQL window:

True, those who didn't have a Skype username got live:something auto assigned usernames. Those who had usernames could login with their username or email address. But most users would login with email addresses as they wouldn't know or remember their auto-assigned usernames. In my case, I have an username but in the microsoft account, it's shown as an alias. I've made my email as the primary alias to be used for login.

> In the result, is it so that the skypename is in the form live:something, and the signin_name in the form [user@email.com](mailto:user@email.com)? What about liveid_membername and msa_pmn?

In the result, skypename and signin_name is my skype username that I set long ago and the liveid_membername is my email ID.
I think email address should be the username because it would always work.

**Comment by suurjaak** [comment]
> Yes, it persists. Maybe it's related to 2-factor authentication or using an authenticator app to login?

Hmm, perhaps indeed. If you have enforced these authentication methods for your account, then it makes sense that password login fails. 

I assume login fails for both your username and e-mail?

**Comment by timea-techgirl** [comment]
> Hmm, perhaps indeed. If you have enforced these authentication methods for your account, then it makes sense that password login fails.
> 
> I assume login fails for both your username and e-mail?

Yes, fails for both username and email.
I think it fails with any kind of error such as logging in from an unknown location.
For example, I logged in with a friend's account who lives in another country and it failed to login but on their computer, it logged in fine with Skyperious. The person got an email about unknown login when I logged in and got an error.
